<a href="https://colab.research.google.com/github/25062891/data-science-toolkit/blob/main/Tutorial_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
n1=np.array([[1,2],[3,4]])
print(n1)

[[1 2]
 [3 4]]


In [ ]:
n2=np.random.random((3,4))
print(n2)

[[0.11240151 0.46965527 0.89731129 0.47861074]
 [0.42024544 0.07286644 0.724553   0.66730864]
 [0.54667395 0.71475126 0.31152045 0.85243338]]


In [ ]:
n3=np.ones((2,2))
print(n3)

[[1. 1.]
 [1. 1.]]


In [ ]:
n4=np.zeros((2,2))
print(n4)

[[0. 0.]
 [0. 0.]]


In [ ]:
n5=np.random.random((6,3))
print(n5)
n5_transpoed=n5.transpose()
print(n5_transpoed,n5_transpoed.shape)

[[0.43692896 0.89110697 0.72300586]
 [0.91107136 0.0560107  0.77352834]
 [0.199688   0.37882234 0.17092987]
 [0.70875122 0.46040061 0.9337456 ]
 [0.35581588 0.34493334 0.85499689]
 [0.50953342 0.70960753 0.1577913 ]]
[[0.43692896 0.91107136 0.199688   0.70875122 0.35581588 0.50953342]
 [0.89110697 0.0560107  0.37882234 0.46040061 0.34493334 0.70960753]
 [0.72300586 0.77352834 0.17092987 0.9337456  0.85499689 0.1577913 ]] (3, 6)


In [ ]:
n6=np.random.random((5,6))
n7=np.random.random((6,7))
dot_product=np.dot(n6, n7)
print(dot_product)

[[1.81353975 1.41533604 0.83177829 1.12628215 2.1044559  1.12273028
  0.8931939 ]
 [1.45921588 1.24058448 1.0569075  1.52868053 1.87104307 1.00571082
  0.92083056]
 [1.79505966 2.21906592 1.21469891 2.01953788 2.7004204  0.98566963
  1.51950867]
 [1.41064091 1.32023212 0.79136058 1.29717349 1.80865342 0.94656565
  0.95598709]
 [2.45557699 2.66846502 1.28803561 2.25091426 3.37120809 1.51274829
  1.91605683]]
